# Standard textclass definition file. Taken from initial LyX source code
# Author : Matthias Ettrich <ettrich@informatik.uni-tuebingen.de>
# Transposed by Pascal AndrИ <andre@via.ecp.fr>
# Heavily modifed and enhanced by several developers.

# Cut & paste from various LyX layouts plus some major modifications
# GOST textclass (c) 2001-2002 Vitaly Lipatov, Boris Balabanov
# Our parts licensed under GPL
# This include file contains all obsolete layouts, kept for
# historical reasons 

Style Engost
  ObsoletedBy		Пункт
End

Style Ensubgost
  ObsoletedBy		Подпункт
End

Style Itemize
  ObsoletedBy		Перечисление
End

Style Enumerate
  ObsoletedBy		ПеречислениеНум
End

#Style Caption
#  ObsoletedBy		ПодписьКРисунку
#End

#Style Caption
#  ObsoletedBy		Caption_for_figure
#End

#Style НаимОрганизации
#  ObsoletedBy		NameOrg
#End
#Style НаимОрганизации
#  ObsoletedBy		Наим_организации
#End

#Style ДатаДокумента
#  ObsoletedBy		Дата_документа
#End

#Style НаимИзделия
#  ObsoletedBy		Наим_изделия
#End

#Style НаимДокумента
#  ObsoletedBy		Наим_документа
#End

Style КЛГИ
  ObsoletedBy		Обозначение
End

Style Нормоконтролер
  ObsoletedBy		Нормоконтролёр
End

# Возвращаемся обратно к нормальным названиям окружений

Style Обычный
  ObsoletedBy		Standard
End

Style Раздел
  ObsoletedBy		Section
End

Style Подраздел
  ObsoletedBy		Subsection
End

Style Подподраздел
  ObsoletedBy		Subsubsection
End

Style Раздел*
  ObsoletedBy		Section*
End

Style Подраздел*
  ObsoletedBy		Subsection*
End

Style Подподраздел*
  ObsoletedBy		Subsubsection*
End
